### ISSUE TITLE
conversion error exception is not handled, causing the bot to exit

### ISSUE THREAD

**Issue by maximmasiutin** [ms609/citation-bot#4288]
You can reproduce it with the following command line command:
```
php process_page.php "Methaniazide" --slow
```

It gives the following error, causing the bot to exit abruptly:
```
 >Checking AdsAbs database no record retrieved.PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "ibm852" in citation-bot/expandFns.php:1507
Stack trace:
#0 citation-bot/expandFns.php(1507): mb_convert_encoding('Methaniazide - ...', 'UTF-8', 'ibm852')
#1 citation-bot/apiFunctions.php(1194): smart_decode('Methaniazide - ...', 'ibm852', 'https://web.arc...')
#2 citation-bot/Page.php(427): expand_templates_from_archives(Array)
#3 citation-bot/expandFns.php(1267): Page->expand_text()
#4 citation-bot/process_page.php(76): edit_a_list_of_pages(Array, Object(WikipediaBot), '| #UCB_CommandL...')
#5 {main}
  thrown in citation-bot/expandFns.php on line 1507

Fatal error: Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "ibm852" in citation-bot/expandFns.php:1507
Stack trace:
#0 citation-bot/expandFns.php(1507): mb_convert_encoding('Methaniazide - ...', 'UTF-8', 'ibm852')
#1 citation-bot/apiFunctions.php(1194): smart_decode('Methaniazide - ...', 'ibm852', 'https://web.arc...')
#2 citation-bot/Page.php(427): expand_templates_from_archives(Array)
#3 citation-bot/expandFns.php(1267): Page->expand_text()
#4 citation-bot/process_page.php(76): edit_a_list_of_pages(Array, Object(WikipediaBot), '| #UCB_CommandL...')
#5 {main}
  thrown in citation-bot/expandFns.php on line 1507
```

**Comment by GlazerMann** [comment]
Some things are Throwable, but not Exceptions.   Fixed.
